print('Vou dissecar algo...')
a = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços? {}'.format(a.isspace()))
print('Só tem números? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minúsculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))
